### ISSUE TITLE
New security groups rules resource seems to need an id

### ISSUE THREAD

**Issue by RichieHowell** [perfectsense/gyro-aws-provider#202]
I receive this when trying to gyro up using the new security group rules

```↓ Loading plugin: gyro:gyro-aws-provider:0.99.1-SNAPSHOT

↓ Loading plugin: gyro:gyro-brightspot-plugin:0.99.1-SNAPSHOT
↓ Loading plugin: gyro:gyro-ssh-plugin:0.99.1-SNAPSHOT
⟳ Refreshed resources: 70

This should've never happened. Please report this as a bug with the following stack trace: gyro.util.Bug: aws::security-group-rules type doesn't have an ID field!
	at gyro.core.scope.converter.ResourceToIdObject.convert(ResourceToIdObject.java:36)
	at gyro.core.scope.converter.ResourceToIdObject.convert(ResourceToIdObject.java:28)
	at com.psddev.dari.util.Converter.convert(Converter.java:381)
	at gyro.core.scope.RootScope.convertValue(RootScope.java:218)
	at gyro.core.resource.DiffableField.setValue(DiffableField.java:164)
	at gyro.core.resource.DiffableType.setValues(DiffableType.java:225)
	at gyro.core.resource.DiffableType.newInternal(DiffableType.java:179)
	at gyro.core.scope.converter.DiffableScopeToDiffable.convert(DiffableScopeToDiffable.java:32)
	at gyro.core.scope.converter.DiffableScopeToDiffable.convert(DiffableScopeToDiffable.java:27)
	at com.psddev.dari.util.Converter.convert(Converter.java:381)
	at com.psddev.dari.util.ObjectToAnyCollection.convert(ObjectToAnyCollection.java:98)
	at com.psddev.dari.util.ObjectToAnyCollection.convert(ObjectToAnyCollection.java:24)
	at com.psddev.dari.util.Converter.convert(Converter.java:381)
	at gyro.core.scope.RootScope.convertValue(RootScope.java:218)
	at gyro.core.resource.DiffableField.setValue(DiffableField.java:164)
	at gyro.core.resource.DiffableType.setValues(DiffableType.java:225)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:520)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:81)
	at gyro.lang.ast.block.ResourceNode.accept(ResourceNode.java:55)
	at gyro.lang.ast.NodeVisitor.visit(NodeVisitor.java:37)
	at gyro.core.scope.NodeEvaluator.lambda$evaluateBody$31(NodeEvaluator.java:341)
	at gyro.core.scope.Defer.execute(Defer.java:50)
	at gyro.core.scope.NodeEvaluator.evaluateBody(NodeEvaluator.java:341)
	at gyro.core.scope.NodeEvaluator.visitFile(NodeEvaluator.java:424)
	at gyro.core.scope.NodeEvaluator.visitFile(NodeEvaluator.java:81)
	at gyro.lang.ast.block.FileNode.accept(FileNode.java:32)
	at gyro.lang.ast.NodeVisitor.visit(NodeVisitor.java:37)
	at gyro.core.scope.NodeEvaluator.lambda$evaluateBody$31(NodeEvaluator.java:341)
	at gyro.core.scope.Defer.execute(Defer.java:50)
	at gyro.core.scope.NodeEvaluator.evaluateBody(NodeEvaluator.java:341)
	at gyro.core.scope.NodeEvaluator.evaluate(NodeEvaluator.java:325)
	at gyro.core.scope.RootScope.evaluate(RootScope.java:317)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:133)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:71)
	at gyro.cli.Gyro.run(Gyro.java:195)
	at gyro.cli.Gyro.main(Gyro.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

Here is the security groups and their rule resources

```
aws::security-group "$(environment)-$(serial)"
    name: "$(project) $(environment) serial-$serial $(layer)"
    vpc: $(aws::vpc base/vpc)
    description: "Allow inbound HTTP/HTTPS traffic"

    tags: {
        Name: "$(project) $(environment) v$(serial) $(layer)",
        'beam.project': $project,
        'beam.serial': $serial,
        'beam.environment': $environment
    }
end

aws::security-group-rules "$(environment)-$(serial)-rules"
    @for type, port -in ['HTTP', 80, 'HTTPS', 443]
        ingress
            description: "Allow inbound $type traffic"
            cidr-block: '0.0.0.0/0'
            protocol: TCP
            from-port: $port
            to-port: $port
        end
    @end
    security-group: $(aws::security-group "$(environment)-$(serial)")
end
```
```    
    aws::security-group operations
        name: "$project operations serial-$serial"
        vpc: $(aws::vpc vpc)
        description: "Limit registry traffic to SSH"
        tags: {
            Name: "$(project) operations v$(serial)",
            'beam.project': $project,
            'beam.serial': $serial
        }
    end

    aws::security-group-rules operations-rules
        @for cidr -in [<List if ip addresses redacted here>]
            ingress
                description: "Allow inbound SSH traffic"
                cidr-block: $cidr
                protocol: "-1"
            end
        @end
        security-group: $(aws::security-group operations)
    end
```

I believe I have the latest provider with the update that brought in security group rules as my files at ~/.m2/repository/gyro/gyro-aws-provider/0.99.1-SNAPSHOT/ are all prefixed with "gyro-aws-provider-0.99.1-20200121.154048-32" which is the day that change was made.

**Comment by RichieHowell** [comment]
Issue has been found:

In a seperate file, one of my security group rules had a $SELF reference which needed to be changed to a $SELF.security-group reference.
