### ISSUE TITLE
Network ACL Configuration Issues

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro-aws-provider#305]
I'm trying to configure a Network ACL Resource and have run into a couple issues.

1) I don't see a way to associate subnets to a Network ACL. I can associate the VPC, but not the subnet.

2) I've added a simple configuration:
```
aws::network-acl network-acl
    vpc: $(aws::vpc vpc)

    ingress-rule
            cidr-block: "0.0.0.0/0"
            protocol : "-1"
            rule-action : "allow"
            rule-number : 100
    end

    ingress-rule
            cidr-block: "195.54.160.21/32"
            protocol : "-1"
            rule-action : "deny"
            rule-number : 99
    end

    egress-rule
             cidr-block: "0.0.0.0/0"
             protocol : '-1'
             rule-action : "allow"
             rule-number : 100
    end
end
```

This is fine for creation. However, on a subsequent Gyro up, I get the following stacktrace:
```
Unexpected error: java.lang.IllegalArgumentException: Multiple entries with same key: Optional[100, egress]=egress-rule 100, egress and Optional[100, egress]=egress-rule 100, egress
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:373)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
	at gyro.core.scope.NodeEvaluator.lambda$copy$37(NodeEvaluator.java:571)
	at java.base/java.util.Optional.map(Optional.java:265)
	at gyro.core.scope.NodeEvaluator.copy(NodeEvaluator.java:571)
	at gyro.core.scope.NodeEvaluator.lambda$visitResource$35(NodeEvaluator.java:525)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:525)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:81)
	at gyro.lang.ast.block.ResourceNode.accept(ResourceNode.java:55)
	at gyro.lang.ast.NodeVisitor.visit(NodeVisitor.java:37)
	at gyro.core.scope.NodeEvaluator.lambda$evaluateBody$31(NodeEvaluator.java:341)
	at gyro.core.scope.Defer.execute(Defer.java:50)
	at gyro.core.scope.NodeEvaluator.evaluateBody(NodeEvaluator.java:341)
	at gyro.core.virtual.VirtualResourceVisitor.visit(VirtualResourceVisitor.java:90)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:532)
	at gyro.core.scope.NodeEvaluator.visitResource(NodeEvaluator.java:81)
	at gyro.lang.ast.block.ResourceNode.accept(ResourceNode.java:55)
	at gyro.lang.ast.NodeVisitor.visit(NodeVisitor.java:37)
	at gyro.core.scope.NodeEvaluator.lambda$evaluateBody$31(NodeEvaluator.java:341)
	at gyro.core.scope.Defer.execute(Defer.java:50)
	at gyro.core.scope.NodeEvaluator.evaluateBody(NodeEvaluator.java:341)
	at gyro.core.scope.NodeEvaluator.visitFile(NodeEvaluator.java:424)
	at gyro.core.scope.NodeEvaluator.visitFile(NodeEvaluator.java:81)
	at gyro.lang.ast.block.FileNode.accept(FileNode.java:32)
	at gyro.lang.ast.NodeVisitor.visit(NodeVisitor.java:37)
	at gyro.core.scope.NodeEvaluator.lambda$evaluateBody$31(NodeEvaluator.java:341)
	at gyro.core.scope.Defer.execute(Defer.java:50)
	at gyro.core.scope.NodeEvaluator.evaluateBody(NodeEvaluator.java:341)
	at gyro.core.scope.NodeEvaluator.evaluate(NodeEvaluator.java:325)
	at gyro.core.scope.RootScope.evaluate(RootScope.java:427)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:179)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:75)
	at gyro.cli.Gyro.run(Gyro.java:205)
	at gyro.cli.Gyro.main(Gyro.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by deepanjan90** [comment]
The PR https://github.com/perfectsense/gyro-aws-provider/pull/306 fixes the refresh issue.

As for associating subnets to Network Acl goes, that association is part of the subnet resource.
https://github.com/perfectsense/gyro-aws-provider/blob/master/src/main/java/gyro/aws/ec2/SubnetResource.java#L69

**Comment by tloisel1** [comment]
This fix resolves my issue.
