### ISSUE TITLE
Can't create S3-website Cloudfront origin

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro-aws-provider#396]
Trying to use an S3-website as a cloudfront origin fails. It seems like Gyro interprets it as an S3 bucket:

```
aws::cloudfront test
    enabled: true

    origin
        id: "S3-Website-test-bucket.s3-website-us-east-1.amazonaws.com"
        domain-name: "test-bucket.s3-website-us-east-1.amazonaws.com"
    end

    default-cache-behavior
        target-origin-id: "S3-Website-test-bucket.s3-website-us-east-1.amazonaws.com"
        viewer-protocol-policy: "redirect-to-https"
        allowed-methods: ["GET", "HEAD"]
        cached-methods: ["GET", "HEAD"]
        headers: ["Origin"]
    end
end
```

```
Error: Can't create aws::cloudfront test resource!

Caused by: Unexpected error: software.amazon.awssdk.services.cloudfront.model.InvalidArgumentException: The parameter Origin DomainName does not refer to a valid S3 bucket. (Service: CloudFront, Status Code: 400, Request ID: 67fdd8b5-07a5-4002-86ab-eeab3f4eb196, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$4(BaseClientHandler.java:214)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.cloudfront.DefaultCloudFrontClient.createDistribution(DefaultCloudFrontClient.java:495)
	at software.amazon.awssdk.services.cloudfront.CloudFrontClient.createDistribution(CloudFrontClient.java:645)
	at gyro.aws.cloudfront.CloudFrontResource.create(CloudFrontResource.java:562)
	at gyro.core.diff.Create.execute(Create.java:85)
	at gyro.core.diff.Diff.executeChange(Diff.java:484)
	at gyro.core.diff.Diff.executeCreateKeepUpdate(Diff.java:417)
	at gyro.core.diff.Diff.execute(Diff.java:408)
	at gyro.core.command.UpCommand.doExecute(UpCommand.java:84)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:182)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:75)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:80)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at gyro.cli.Gyro.run(Gyro.java:262)
	at gyro.cli.Gyro.main(Gyro.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by beetlebugorg** [comment]
Should this be?

```
    origin
        id: "S3-Website-test-bucket.s3-website-us-east-1.amazonaws.com"
        domain-name: "test-bucket.s3.amazonaws.com"
    end
```

**Comment by deepanjan90** [comment]
I think the feature being talked about is setting an origin to point at a `s3 website endpoint` instead of a `s3 bucket endpoint`

The issue at large is that, the way the origin api works is that it needs either an `s3 origin` or a `custom origin`

The following is the error thrown by aws when neither is provided.
`software.amazon.awssdk.services.cloudfront.model.InvalidOriginException: The specified origin server does not exist or is not valid. (Service: CloudFront, Status Code: 400, Request ID: f79b9fea-9206-41c5-a90c-69b9ba5fcf8f, Extended Request ID: null)`

So what we currently end up doing is if neither a custom-origin or a s3-origin is provided, gyro auto configures one s3-origin
https://github.com/perfectsense/gyro-aws-provider/blob/master/src/main/java/gyro/aws/cloudfront/CloudFrontOrigin.java#L103-L105

Now in case the domain name is not a bucket, it needs a custom-origin rather than a s3-origin, which causes the issue

For refernece: https://github.com/aws/aws-sdk-js/issues/2368#issuecomment-440756994
