### ISSUE TITLE
Can't delete Security Group Rules using non-default credentials

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro-aws-provider#398]
I created a security group rules with non-default credentials:

```
aws::security-group sg-group
    name: sg-group
    vpc: $(aws::vpc vpc)
    description: "Allow inbound HTTP/HTTPS traffic"
    @uses-credentials: us-east-1
end

aws::security-group-rules sg-group-rules
    security-group: $(aws::security-group sg-group)
    @uses-credentials: us-east-1

    @for type, port -in ['HTTP', 80, 'HTTPS', 443]
        ingress
            description: "Allow inbound $type traffic"
            cidr-block: '0.0.0.0/0'
            protocol: TCP
            from-port: $port
            to-port: $port
            @uses-credentials: us-east-1
        end
    @end
end
```

This created them fine, but when I go to delete them:
```
$ gyro up
⟳ Refreshed resources: 129

Looking for changes...

- Delete aws::security-group sg-group (sg-0c621bff48d8981e1)
- Delete aws::security-group-rules sg-group-rules (aws::security-group sg-group)
    - Delete ingress 80 80 tcp 0.0.0.0/0
    - Delete ingress 443 443 tcp 0.0.0.0/0

Are you sure you want to change resources? (y/N) y

- Deleting ingress 443 443 tcp 0.0.0.0/0 for aws::security-group-rules sg-group

Error: Can't delete ingress 443 443 tcp 0.0.0.0/0 resource!

Caused by: Unexpected error: software.amazon.awssdk.services.ec2.model.Ec2Exception: The security group 'sg-0c621bff48d8981e1' does not exist (Service: Ec2, Status Code: 400, Request ID: 3d512934-c220-4a58-8bfb-47ba52b22b72, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:133)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:159)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:112)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.ec2.DefaultEc2Client.revokeSecurityGroupIngress(DefaultEc2Client.java:31111)
	at software.amazon.awssdk.services.ec2.Ec2Client.revokeSecurityGroupIngress(Ec2Client.java:52531)
	at gyro.aws.ec2.SecurityGroupIngressRuleResource.delete(SecurityGroupIngressRuleResource.java:46)
	at gyro.core.diff.Delete.execute(Delete.java:60)
	at gyro.core.diff.Diff.executeChange(Diff.java:484)
	at gyro.core.diff.Diff.executeDelete(Diff.java:456)
	at gyro.core.diff.Diff.executeDelete(Diff.java:452)
	at gyro.core.diff.Diff.execute(Diff.java:411)
	at gyro.core.command.UpCommand.doExecute(UpCommand.java:84)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:182)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:75)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:80)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at gyro.cli.Gyro.run(Gyro.java:262)
	at gyro.cli.Gyro.main(Gyro.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

This appears to be using the default credentials to search for the SG group rules.

After I had removed the rules manually, the Gyro was able to delete the security group.

**Comment by deepanjan90** [comment]
The PR also eliminates the need to use `@uses-credentials` as part of the subresource block
As an example when defining the security group rules
```


aws::security-group-rules sg-group-rules
    security-group: $(aws::security-group sg-group)
    @uses-credentials: us-east-1

    @for type, port -in ['HTTP', 80, 'HTTPS', 443]
        ingress
            description: "Allow inbound $type traffic"
            cidr-block: '0.0.0.0/0'
            protocol: TCP
            from-port: $port
            to-port: $port
        end
    @end
end
```

**Comment by tloisel1** [comment]
I was able to create and delete security groups using the credentials directive.
