### ISSUE TITLE
Security Group Rules java.lang.NullPointerException

### ISSUE THREAD

**Issue by ssnyder-sme** [perfectsense/gyro-aws-provider#569]
I was able to create security group rules in Gyro, but after they were successfully deployed, anytime I run `gyro up` it throws a null pointer exception trying to refresh the rules.

Success:

![Screen Shot 2022-06-22 at 5 20 12 PM](https://user-images.githubusercontent.com/69162122/175181881-d6ee91c7-e358-4f54-942b-e95efe05269d.png)

![Screen Shot 2022-06-22 at 5 20 23 PM](https://user-images.githubusercontent.com/69162122/175181888-b1adfea0-0b80-4775-a4db-5b1a60d8d07b.png)

Failure:

Error: Can't refresh aws::security-group-rules k8s-dev resource!

Caused by: Unexpected error: java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at gyro.core.command.AbstractConfigCommand.refreshResources(AbstractConfigCommand.java:260)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:174)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:75)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:80)
	at gyro.core.command.AbstractCommand.call(AbstractCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at gyro.cli.Gyro.run(Gyro.java:267)
	at gyro.cli.Gyro.main(Gyro.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException
	at gyro.aws.ec2.SecurityGroupRulesResource.lambda$getSecurityGroup$1(SecurityGroupRulesResource.java:249)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
	at software.amazon.awssdk.services.ec2.model.DescribeSecurityGroupsRequest$BuilderImpl.lambda$filters$0(DescribeSecurityGroupsRequest.java:1571)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at software.amazon.awssdk.services.ec2.model.DescribeSecurityGroupsRequest$BuilderImpl.filters(DescribeSecurityGroupsRequest.java:1571)
	at gyro.aws.ec2.SecurityGroupRulesResource.lambda$getSecurityGroup$2(SecurityGroupRulesResource.java:247)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
	at software.amazon.awssdk.services.ec2.Ec2Client.describeSecurityGroups(Ec2Client.java:33266)
	at gyro.aws.ec2.SecurityGroupRulesResource.getSecurityGroup(SecurityGroupRulesResource.java:246)
	at gyro.aws.ec2.SecurityGroupRulesResource.refresh(SecurityGroupRulesResource.java:133)
	at gyro.core.command.AbstractConfigCommand.lambda$refreshResources$7(AbstractConfigCommand.java:228)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by deepanjan90** [comment]
@ssnyder-sme let me know if this works for you, and we can cut a patch release for with this fix for you to use.

**Comment by ssnyder-sme** [comment]
How can I target your Pull Request code change and test locally?

**Comment by deepanjan90** [comment]
You can build the PR locally (root of gyro-aws-provider and running `./gradlew clean && ./gradlew`)
It will create a local snapshot (gyro-aws-provider), 

Then in your init.gyro file you can replace 
`@plugin: 'gyro:gyro-aws-provider:1.4.7'`
with
`@plugin: 'gyro:gyro-aws-provider:1.5.0-SNAPSHOT'`

and now it will point to the locally build provider in this case the pr

**Comment by ssnyder-sme** [comment]
Excellent. That worked. Was able to just gyro up successfully and even had it modify existing security group rules. Thank you!! Ready for a release to get tagged.

**Comment by deepanjan90** [comment]
We will have a patch release soon.

**Comment by ssnyder-sme** [comment]
Much appreciated :-D

**Comment by deepanjan90** [comment]
patch release `gyro-aws-provider-1.4.9` is ready to be used.

**Comment by ssnyder-sme** [comment]
Thank you very much
